name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Docker (Using yum)
      - name: Install Docker
        run: |
          sudo yum update -y
          sudo yum remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine containerd runc || true
          sudo yum install -y yum-utils
          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          sudo yum install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      # Step 3: Build and Start Services for Testing
      - name: Start Test Services
        run: |
          docker compose -f ./docker-compose-tests.yml up -d --build

      # Step 4: Run Trace-Based Tests
      - name: Run Trace-Based Tests
        working-directory: ./test/tracetesting
        run: |
          make run-tracetesting

      # Step 5: Rollback on Failure
      - name: Rollback on Failure
        if: failure()
        run: |
          echo "Tests failed. Cleaning up services..."
          docker compose -f ./docker-compose-tests.yml down || echo "Rollback failed."

      # Step 6: Stop Test Services After Completion
      - name: Stop Test Services
        if: always()
        run: |
          echo "Stopping services..."
          docker compose -f ./docker-compose-tests.yml down

      # Step 7: Display Success Message
      - name: Display Success Message
        if: success()
        run: echo "CI/CD pipeline executed successfully!"
