# Copyright 2024 ENPM818N_Group_Project4
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Kubernetes CLI (kubectl)
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -LO "https://dl.k8s.io/release/v1.27.5/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 3: Set up AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Update kubeconfig for EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name otel-demo-cluster

      # Step 5: Apply Namespace YAML
      - name: Apply Namespace
        run: |
          kubectl apply -f ./opentelemetry-split/Namespaces/namespaces_1.yaml

      # Step 6: Apply Other Resources Recursively
      - name: Deploy Application
        run: |
          kubectl apply -R -f ./opentelemetry-split/

      # Step 7: Verify Deployment
      - name: Verify Pods
        run: |
          kubectl get pods -n otel-demo

      # Step 8: Rollback on Failure
      - name: Rollback on Failure
        if: failure()
        run: |
          kubectl rollout undo deployment opentelemetry-demo-frontend -n otel-demo

      - name: Display Success Message
        run: echo "CI/CD pipeline executed successfully!"
