name: kube deployment

on:
  workflow_call:

jobs:
  kubernetes-deployment-apply:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step:
          - accountingservice
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - flagd
          - frauddetectionservice
          - frontend
          - frontendproxy
          - grafana
          - imageprovider
          - jaeger
          - kafka
          - loadgenerator
          - open
          - paymentservice
          - productcatalogservice
          - prometheus
          - quoteservice
          - recommendationservice
          - shippingservice
          - valkey

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EKS cluster
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name otel-demo-cluster --region us-east-1

      - name: Deploy Application
        run: |
          kubectl apply -R -f ./opentelemetry-split/Deployments/deployment_${{ matrix.step }}.yaml


  kubernetes-failure-rollout:
    needs: kubernetes-deployment-apply
    runs-on: ubuntu-latest
    if: failure()
    strategy:
      matrix:
        step:
          - accountingservice
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - flagd
          - frauddetectionservice
          - frontend
          - frontendproxy
          - grafana
          - imageprovider
          - jaeger
          - kafka
          - loadgenerator
          - open
          - paymentservice
          - productcatalogservice
          - prometheus
          - quoteservice
          - recommendationservice
          - shippingservice
          - valkey

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EKS cluster
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name otel-demo-cluster --region us-east-1

      - name: Rollback deployment ${{ matrix.step }}
        run: |
          if kubectl rollout history deployment/opentelemetry-demo-${{ matrix.step }} > /dev/null 2>&1; then
            echo "Rolling back ${{ matrix.step }}..."
            kubectl rollout undo deployment/opentelemetry-demo-${{ matrix.step }}
            kubectl rollout status deployment/opentelemetry-demo-${{ matrix.step }} --timeout=60s
          else
            echo "No previous deployment to rollback to for ${{ matrix.step }}."
          fi

      - name: Log rollback success
        run: echo "Rollback completed for ${{ matrix.step }}."
