name: kube deployment

on:
  workflow_call:

jobs:
  update-kubeconfig-and-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Update kubeconfig for EKS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name otel-demo-cluster

      - name: Apply Namespace
        run: |
          kubectl apply -f ./opentelemetry-split/Namespaces/namespaces_1.yaml

  kubernetes-deployment-apply:
    runs-on: ubuntu-latest
    needs: update-kubeconfig-and-namespace
    strategy:
      matrix:
        step:
          - accountingservice
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - flagd
          - frauddetectionservice
          - frontend
          - frontendproxy
          - grafana
          - imageprovider
          - jaeger
          - kafka
          - loadgenerator
          - open
          - paymentservice
          - productcatalogservice
          - prometheus
          - quoteservice
          - recommendationservice
          - shippingservice
          - valkey

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EKS cluster
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name otel-demo-cluster --region us-east-1

      - name: Deploy Application
        run: |
          kubectl apply -R -f ./opentelemetry-split/Deployments/deployment_${{ matrix.step }}.yaml

      - name: Check deployment status
        run: |
          kubectl rollout status deployment/opentelemetry-demo-${{ matrix.step }}

  kubernetes-failure-rollout:
    needs: kubernetes-deployment-apply
    runs-on: ubuntu-latest
    if: failure()
    strategy:
      matrix:
        step:
          - accountingservice
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - flagd
          - frauddetectionservice
          - frontend
          - frontendproxy
          - grafana
          - imageprovider
          - jaeger
          - kafka
          - loadgenerator
          - open
          - paymentservice
          - productcatalogservice
          - prometheus
          - quoteservice
          - recommendationservice
          - shippingservice
          - valkey

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EKS cluster
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name otel-demo-cluster --region us-east-1

      - name: Rollback deployment ${{ matrix.step }}
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-${{ matrix.step }}

      - name: Check rollback status
        run: |
          kubectl rollout status deployment/opentelemetry-demo-${{ matrix.step }}
