name: kube deployment

on:
  workflow_call:

jobs:
  kubernetes-deployment-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EKS cluster
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name otel-demo-cluster --region us-east-1

      - name: Deploy Application
        run: |
          kubectl apply -f ./kubernetes/opentelemetry-demo.yaml

      - name: Verify Pods
        run: |
          echo "Waiting for all pods to be ready in the otel-demo namespace..."
          kubectl wait --for=condition=Ready pods --all --namespace otel-demo --timeout=300s
          echo "All pods are ready."

  kubernetes-failure-rollout:
    needs: kubernetes-deployment-apply
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EKS cluster
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name otel-demo-cluster --region us-east-1

      - name: Rollback deployment
        run: |
          echo "Rolling back deployments from combined file..."
          kubectl rollout undo -f ./kubernetes/opentelemetry-demo.yaml
          kubectl rollout status -f ./kubernetes/opentelemetry-demo.yaml --timeout=60s

      - name: Log rollback success
        run: echo "Rollback completed for all deployments in the combined file."
